### ISSUE TITLE
Distances aren't rounded properly

### ISSUE THREAD

**Issue by awenelo** [WCI-Computer-Science/WCI-Walks#24]
Something is causing distances to not be rounded properly. Since @scott-22's distances are being imported from google fit, I'm assuming this is something wrong with the google fit importing. Updating distances fixes it.
(Image from the leaderboard)
![Screen Shot 2021-02-16 at 9 19 07 AM](https://user-images.githubusercontent.com/56133692/108075449-60d54080-7038-11eb-92e3-05f92b4c8b84.png)

**Comment by scott-22** [comment]
The problem is with floating point rounding, so I changed the database to use a numeric type with fixed precision.
